# Notebook for exploring and understanding the depmap datasets and doing basic data cleaning

In [1]:
import sys
import os
import pandas as pd
import numpy as np
import matplotlib as mpl
from matplotlib import pyplot as plt
import seaborn as sb

## looking at the depmap crispr data

In [8]:
screen_gene_effect = pd.read_csv('./new_data/crispr_depmap_public/DepMap_Public_24Q4/ScreenGeneEffect.csv', header = 0, index_col = 0)

In [11]:
screen_gene_effect.shape

(1401, 18435)

In [7]:
crispr_gene_effect = pd.read_csv('./new_data/crispr_depmap_public/DepMap_Public_24Q4/CRISPRGeneEffect.csv', header = 0, index_col = 0)

In [12]:
crispr_gene_effect.shape

(1178, 17916)

In [15]:
screen_gene_effect.loc['SC-001041.AV01']

A1BG (1)               -0.113535
A1CF (29974)            0.114015
A2M (2)                -0.038345
A2ML1 (144568)          0.135166
A3GALT2 (127550)       -0.063006
                          ...
PKD1L2 (114780)              NaN
RPL15 (6138)                 NaN
RPSA (3921)                  NaN
SIGLEC14 (100049587)         NaN
SUMO2 (6613)                 NaN
Name: SC-001041.AV01, Length: 18435, dtype: float64

In [16]:
crispr_gene_effect.loc['ACH-001041']

A1BG (1)           -0.234529
A1CF (29974)       -0.008447
A2M (2)             0.066081
A2ML1 (144568)      0.100099
A3GALT2 (127550)   -0.146146
                      ...
ZYG11A (440590)    -0.144280
ZYG11B (79699)      0.074014
ZYX (7791)         -0.117943
ZZEF1 (23140)      -0.235554
ZZZ3 (26009)       -0.098776
Name: ACH-001041, Length: 17916, dtype: float64

In [17]:
meta = pd.read_csv('./new_data/crispr_depmap_public/DepMap_Public_24Q4/Model.csv', header = 0, index_col = 0)

In [ ]:
meta.loc[meta['StrippedCellLineName'] == '786O',:]

,PatientID,CellLineName,StrippedCellLineName,DepmapModelType,OncotreeLineage,OncotreePrimaryDisease,OncotreeSubtype,OncotreeCode,PatientSubtypeFeatures,RRID,...,EngineeredModelDetails,CulturedResistanceDrug,PublicComments,CCLEName,HCMIID,ModelAvailableInDbgap,ModelSubtypeFeatures,WTSIMasterCellID,SangerModelID,COSMICID
ModelID,,,,,,,,,,,,,,,,,,,,,
ACH-000649,PT-4QH2lI,786-O,786O,CCRCC,Kidney,Renal Cell Carcinoma,Renal Clear Cell Carcinoma,CCRCC,NaN,CVCL_1051,...,NaN,NaN,NaN,786O_KIDNEY,NaN,Available in SRA,NaN,301.0,SIDM00125,905947.0

In [35]:
crispr_gene_effect.loc['ACH-000649']

A1BG (1)           -0.225722
A1CF (29974)       -0.051713
A2M (2)            -0.020376
A2ML1 (144568)      0.104287
A3GALT2 (127550)   -0.066424
                      ...
ZYG11A (440590)    -0.061812
ZYG11B (79699)     -0.133118
ZYX (7791)         -0.272024
ZZEF1 (23140)      -0.098781
ZZZ3 (26009)       -0.177923
Name: ACH-000649, Length: 17916, dtype: float64

In [19]:
dataset = pd.read_csv("input/combined_DepMap_21Q3.csv")

In [28]:
len(set(dataset['cell_line_name']).intersection(meta['StrippedCellLineName']))

420

In [24]:
dataset

,cell_line_name,SHOC2,NDUFA12,SDAD1,FAM98A,ZNF253,HIST1H2BF,SYNE2,BATF2,MYSM1,...,BRD-K98557884-001-01-6::2.5::MTS004,BRD-K99077012-001-01-9::2.332734192::MTS004,BRD-K99199077-001-16-1::2.603211317::MTS004,BRD-K99431849-001-01-7::2.500018158::MTS004,BRD-K99447003-335-04-1::2.37737659::MTS004,BRD-K99506538-001-03-8::2.5::MTS004,BRD-K99616396-001-05-1::2.499991421::MTS004,BRD-K99879819-001-02-1::2.5187366::MTS004,BRD-K99919177-001-01-3::2.5::MTS004,BRD-M63173034-001-03-6::2.64076472::MTS004
0,786O,-0.170480,-0.001571,-0.508840,0.100710,-0.500540,0.032066,0.037976,-0.064822,-0.130860,...,0,0,0,0,0,1,0,0,0,1
1,786O,-0.211080,-0.062542,-0.553700,-0.123550,-0.568960,-0.015012,0.103930,-0.006396,-0.077251,...,0,0,0,0,0,1,0,0,0,1
2,786O,-0.132900,-0.092734,-0.498760,-0.067310,-0.719060,0.026317,0.115370,-0.194120,-0.116930,...,0,0,0,0,0,1,0,0,0,1
3,A2780,-0.779830,-0.042110,-0.394270,0.003978,-0.877140,-0.105480,0.011407,-0.074964,-0.280240,...,0,0,0,0,1,0,0,0,1,0
4,A2780,-0.845280,0.238360,-0.761220,0.075909,-1.114000,-0.243390,0.170000,-0.445180,-0.182150,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,CORL105,-0.251690,-0.149800,-0.460510,-0.019392,-0.459950,-0.052023,0.033007,-0.234380,0.054896,...,0,0,0,0,0,0,0,0,0,0
920,T47D,0.025242,-0.118210,-0.213480,-0.042699,-0.443050,0.064490,0.009822,-0.148860,0.102340,...,0,1,0,1,0,1,0,0,0,0
921,T47D,0.002724,-0.076599,-0.231810,-0.114660,-0.536980,0.048041,-0.044399,-0.113580,0.071336,...,0,1,0,1,0,1,0,0,0,0
922,PANC0504,-0.239900,0.191380,-0.013809,0.082371,-0.153120,0.256750,-0.174290,-0.325430,-0.174570,...,0,0,0,1,0,0,1,0,0,0
923,PANC0504,-0.319190,-0.187390,-0.098321,0.334470,-0.081403,0.192150,0.029128,-0.272240,0.005407,...,0,0,0,1,0,0,1,0,0,0

In [53]:
sum(dataset.loc[dataset['cell_line_name'] == 'T47D',].iloc[:,-4686:].iloc[0,:]-dataset.loc[dataset['cell_line_name'] == 'T47D',].iloc[:,-4686:].iloc[1,:])

0

In [50]:
np.corrcoef(dataset.loc[dataset['cell_line_name'] == 'PANC0504',:].iloc[:,1:])

array([[1.        , 0.77515057],
       [0.77515057, 1.        ]])

In [46]:
np.array(dataset.loc[dataset['cell_line_name'] == 'T47D',:].values[:,1:])

array([[0.025242, -0.11821, -0.21348, ..., 0, 0, 0],
       [0.0027236, -0.076599, -0.23181, ..., 0, 0, 0]],
      shape=(2, 22337), dtype=object)

In [26]:
'786O' in meta['StrippedCellLineName']

False